FROM php:7.4-fpm

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-install \
        zip \
        intl \
        mysqli \
        pdo pdo_mysql

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY ./ /var/www/dm-project/
WORKDIR /var/www/dm-project/